#!/bin/bash

let nev=1000
let sqrts=200

if [ $# -ge 1 ]; then
  let nev=$1
  if [ $# -ge 2 ]; then
    let sqrts=$2
  fi
fi

echo "nev=$nev sqrts=$sqrts"

dir=$(pwd)
cd $SIMGEN
root -l 'GenerateEvents.C('$nev','$sqrts')'
cd $dir
