/********************************************************************
* SimGenDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SimGenDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSimGenDict();
extern void G__cpp_setup_inheritanceSimGenDict();
extern void G__cpp_setup_typetableSimGenDict();
extern void G__cpp_setup_memvarSimGenDict();
extern void G__cpp_setup_globalSimGenDict();
extern void G__cpp_setup_memfuncSimGenDict();
extern void G__cpp_setup_funcSimGenDict();
extern void G__set_cpp_environmentSimGenDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EventLoop.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SimGenDictLN_TClass;
extern G__linked_taginfo G__SimGenDictLN_TBuffer;
extern G__linked_taginfo G__SimGenDictLN_TMemberInspector;
extern G__linked_taginfo G__SimGenDictLN_TObject;
extern G__linked_taginfo G__SimGenDictLN_TString;
extern G__linked_taginfo G__SimGenDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__SimGenDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__SimGenDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SimGenDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimGenDictLN_TClonesArray;
extern G__linked_taginfo G__SimGenDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SimGenDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimGenDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SimGenDictLN_TTree;
extern G__linked_taginfo G__SimGenDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__SimGenDictLN_TPythia6;
extern G__linked_taginfo G__SimGenDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__SimGenDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimGenDictLN_EventLoop;

/* STUB derived class for protected member access */
